-- =============================================================================
-- Enquiries
-- Every contact-form submission. Written by the website through
-- public.create_website_enquiry() (workflows migration, service role only);
-- read and managed by admins. "In the CRM" means lead_id is set (FK added in the
-- CRM migration). No IP addresses or hashes are kept on the enquiry itself.
-- =============================================================================

create table public.enquiries (
  id uuid primary key default gen_random_uuid(),
  -- Generated by the form when it loads; a double-submitted form is stored once.
  submission_id uuid unique,
  name text not null check (char_length(btrim(name)) between 2 and 120),
  email text not null check (char_length(email) between 3 and 254 and email like '%_@_%'),
  phone text check (char_length(phone) <= 40),
  lot text check (char_length(lot) <= 20),
  interest text not null default 'other' check (interest in ('prebook', 'site_visit', 'pricing', 'other')),
  message text check (char_length(message) <= 2000),
  preferred_viewing_at timestamptz,
  source_path text check (char_length(source_path) <= 300),
  status text not null default 'new' check (status in ('new', 'read', 'archived')),
  lead_id uuid,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index enquiries_created_at_idx on public.enquiries (created_at desc);
create index enquiries_status_created_at_idx on public.enquiries (status, created_at desc);
create index enquiries_email_idx on public.enquiries (lower(email));

create trigger enquiries_set_updated_at
  before update on public.enquiries
  for each row execute function private.set_updated_at();

alter table public.enquiries enable row level security;
revoke all on table public.enquiries from anon;
grant select, insert, update, delete on table public.enquiries to authenticated;
grant all on table public.enquiries to service_role;

create policy "enquiries_admin_all" on public.enquiries
  for all to authenticated
  using ((select private.is_admin()))
  with check ((select private.is_admin()));

-- Activity feed entries.
create or replace function private.enquiries_activity()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if tg_op = 'INSERT' then
    perform private.log_activity(
      'enquiry', new.id, 'created',
      format('New enquiry from %s', new.name),
      jsonb_build_object('interest', new.interest, 'lot', new.lot)
    );
  elsif tg_op = 'DELETE' then
    perform private.log_activity('enquiry', old.id, 'deleted', format('Enquiry from %s deleted', old.name));
  end if;
  return coalesce(new, old);
end;
$$;

create trigger enquiries_activity
  after insert or delete on public.enquiries
  for each row execute function private.enquiries_activity();
